### ISSUE TITLE
Execution failed for task ':react-native-keys:externalNativeBuildCleanRelease'

### ISSUE THREAD

**Issue by crzycoder** [numandev1/react-native-keys#1]
`A problem occurred starting process 'command '/Users/apple/Library/Android/sdk/cmake/3.6.4111459/bin/cmake''`

<img width="1675" alt="Screenshot 2021-04-08 at 11 26 34 AM" src="https://user-images.githubusercontent.com/43851308/113978344-4875eb00-985d-11eb-9529-251085a5ee3b.png">

**Comment by nomi9995** [comment]
@crzycoder i will reproduce it on my side after office and fix it

**Comment by nomi9995** [comment]
@crzycoder it is not reproducing on my side. 
can you try this

Build -> Refresh Linked C++ Projects

**Comment by kacianoghelere** [comment]
Just installed the library on my project and encountered the very same error.

**Comment by numandev1** [comment]
fixed by https://github.com/numandev1/react-native-keys/pull/5
