### ISSUE TITLE
Need New Architecture Turbo module support

### ISSUE THREAD

**Issue by numandev1** [numandev1/react-native-keys#10]

**Comment by MasonLe2497** [comment]
Follow [PR](https://github.com/numandev1/react-native-keys/pull/37)

**Comment by pritsawa** [comment]
Try this in meantime https://www.youtube.com/watch?v=J0OSn7s9YiA&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=9

**Comment by numandev1** [comment]
closed by #37
