### ISSUE TITLE
Add support key path

### ISSUE THREAD

**Issue by MasonLe2497** [numandev1/react-native-keys#23]
### Current behavior
I have multiple env, i want to store env to 1 folders(env/...). But i saw this library only support env file name, env file must belong to root folder.
<img width="674" alt="image" src="https://github.com/numandev1/react-native-keys/assets/43195241/4e35c8d2-eab4-4254-91e7-560ade40c572">

### Expected behavior
Custom path env instead file name.
### Platform

- [X] Android
- [X] iOS

### React Native Version
0.71.8

**Comment by numandev1** [comment]
@MasonLe2497 I did not understand your question fully
so you have one env folder and in the env folder, you have different environment files like dev `keys.development.json` `keys.production.json` etc and you wanna access to these env files from that folder, am I right?

**Comment by numandev1** [comment]
@MasonLe2497 you can write a filename like below to support env file from folder/directory
```
export KEYSFILE=envs/keys.1.json // for one secheme

export KEYSFILE=envs/keys.2.json // for second scheme

export KEYSFILE=envs/keys.3.json // for third scheme

export KEYSFILE=envs/keys.2.json // for forth scheme
```

**Comment by MasonLe2497** [comment]
i added script KEYSFILE="env/dev.json" . but i get error: keys.development.json not found.
my code:
<img width="520" alt="image" src="https://github.com/numandev1/react-native-keys/assets/43195241/93a3dca5-1e73-4f17-9b2f-e1e98ac5b3b1">

**Comment by numandev1** [comment]
@MasonLe2497 can you write `export` in front of KEYSFILE like this  and test
```
export KEYSFILE="env/dev.json
```

**Comment by MasonLe2497** [comment]
@numandev1 thanks,. i'll try it

**Comment by numandev1** [comment]
@MasonLe2497 let me know when you test it

**Comment by numandev1** [comment]
@MasonLe2497 did you try?

**Comment by MasonLe2497** [comment]
Hi @numandev1 , (the solution)[https://github.com/numandev1/react-native-keys/issues/23#issuecomment-1649306807] working, thanks

**Comment by numandev1** [comment]
close by [the solution](https://github.com/numandev1/react-native-keys/issues/23#issuecomment-1649306807)
