### ISSUE TITLE
[Docs issue] Please add Proguard(or Dexguard) troubleshooting comment

### ISSUE THREAD

**Issue by YangJonghun** [numandev1/react-native-keys#27]
### Current behavior
I get an error when using Proguard, but there is no guide in the documentation about it.

### Platform

- [X] Android
- [ ] iOS

### Expected behavior
I would you like to add below comment related to Proguard

### Problems with Proguard

When Proguard is enabled (which it is by default for Android release builds), it can rename the `BuildConfig` Java class in the minification process and prevent React Native Config from referencing it. To avoid this, add an exception to `android/app/proguard-rules.pro`:

    -keep class com.mypackage.BuildConfig { *; }

`com.mypackage` should match the `package` value in your `app/src/main/AndroidManifest.xml` file.

If using Dexguard, the shrinking phase will remove resources it thinks are unused. It is necessary to add an exception to preserve the build config package name.

    -keepresources string/build_config_package
    
(above comment from `react-native-config`'s [ReadMe](https://github.com/luggit/react-native-config#troubleshooting))

**Comment by numandev1** [comment]
@YangJonghun thanks a lot for point out this issue
