### ISSUE TITLE
Release build not work with iOS simulator

### ISSUE THREAD

**Issue by YangJonghun** [numandev1/react-native-keys#34]
### Current behavior
Release build not work with iOS simulator

below build error occurred
```
Undefined symbol: _BIO_f_base64
Undefined symbol: _BIO_free_all
...
```

because `react-native-keys` use `OpenSSL-Universal`
It can be avoid to make `OpenSSL.xcframework` into dynamic framework (via using `Frameworks, Libraries, and Embedded Content` option)
but I'm not sure this is best solution

### Expected behavior
Release build work properly with iOS simulator

### Platform

- [ ] Android
- [X] iOS

**Comment by numandev1** [comment]
can you tell me about your react native version?

**Comment by numandev1** [comment]
https://stackoverflow.com/a/76455587/8079868 can you try these solutions? ![image](https://github.com/numandev1/react-native-keys/assets/36044436/79d29793-8f08-4acf-8792-9bd520eba0fe)

**Comment by YangJonghun** [comment]
Oh I didn't read the document carefully enough
I'm sorry to bother you
anyway I tried `Solution 1` and it works
(but I'm not sure this is best solution)

I appreciate your quick response
I'll close this issue

**Comment by numandev1** [comment]
@YangJonghun thanks a lot for pointing out issues, hopefully we will make this package more stable and maintainable together

i think, this issue only happens on RN 0.65 to 0.90, it does not happen on RN >= 70
