### ISSUE TITLE
Keys not working on iOS

### ISSUE THREAD

**Issue by dayaki** [numandev1/react-native-keys#44]
### Current behavior
Installed the package, did pod install, created keys.development.json file with secure entries:

``{
  "secure": {
    "APP_URL": "website-url.com",
  }
}
``

but I can't access them, they return empty when I do `console.log('keys', Keys.secureFor('APP_URL'))`

### Expected behavior
`console.log('keys 2', Keys.secureFor('APP_URL'))` should return the expected data in `secure: { "APP_URL": "url"}`

### Platform
- [X] iOS

### Versions
React Native Version -> `0.71.11`
React Native Keys -> `0.5.14`

**Comment by numandev1** [comment]
@dayaki did you add this script in pre-action
```
    export KEYSFILE = "keys.development.json"
   "${SRCROOT}/../node_modules/react-native-keys/keysIOS.js"
```

**Comment by dayaki** [comment]
yes sure

**Comment by numandev1** [comment]
@dayaki can you connect with me on LinkedIn https://www.linkedin.com/in/numandev/ where we can send zoom session

**Comment by dayaki** [comment]
@numandev1 I figured it out...I was adding the scheme script in run pre-action instead of build pre-action. Would you advice the`keys.*.json` files be added to git or be `.gitignore`

**Comment by numandev1** [comment]
@dayaki Yes, I advise you to add product keys.json into gitignore not dev or staging otherwise you have to involve in the setup of every new developer in the team

**Comment by numandev1** [comment]
@dayaki would you like to make PR for improve documentation of this package or you can give feedback i can change, thanks
