### ISSUE TITLE
cmake error on Android Build

### ISSUE THREAD

**Issue by barzin144** [numandev1/react-native-keys#46]
Hi, I hope your doing well,
I added react-native-keys to my project everything works find in ios, but for android I can't build the project and I've got this error
> Execution failed for task ':react-native-keys:generateJsonModelDebug'
> executing external native build for cmake ..../node_modules/react-native/keys/android/CMakeLists.txt
 -------
React-native version 0.63
classpath("com.android.tools.build:gradle:4.1.3")
gradle-wrapper: dradle-7.3.3-all.zip

**Comment by numandev1** [comment]
@barzin144 what version of react-native-keys, you are using?
I did not test this package on `react-native@0.63.0` , can you provide me reproducable GitHub example so I can fix it quickly

**Comment by chanphiromsok** [comment]
expo prebuild also doesnt not work can not find keys.*.json  when I log Keys import from 'react-native-keys' it show other data like APPLICATION_ID BUILD_TYPE DEBUG instead

**Comment by numandev1** [comment]
@chanphiromsok Expo support in this package is in progress, My question from you is, how do you manage different Xcode schemes and Android different variants?👀

**Comment by chanphiromsok** [comment]
> @chanphiromsok Expo support in this package is in progress, My question from you is, how do you manage different Xcode schemes and Android different variants?👀

I haven't try on IOS yet I test only android 😅

**Comment by barzin144** [comment]
> @barzin144 what version of react-native-keys, you are using? I did not test this package on `react-native@0.63.0` , can you provide me reproducable GitHub example so I can fix it quickly

I'm using verions 0.6.0
I've update classpath com.android.tools.build:gradle to 4.2.2, But it made me to update other packages after updating every thing I've succeed to build but when I've tried to run on simulator I've got the error like can't call method async...

**Comment by numandev1** [comment]
@chanphiromsok how do you manage android variants? 
```
 buildTypes {
        debug {
            signingConfig signingConfigs.debug
            applicationIdSuffix ".dev"
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.release
            applicationIdSuffix ".lava"
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        releasestaging {
            initWith release
            applicationIdSuffix ".dev"
            matchingFallbacks = ['release']
        }
    }
```

**Comment by numandev1** [comment]
@barzin144 i did not experience this error, can we both look it on zoom?

**Comment by chanphiromsok** [comment]
> @chanphiromsok how do you manage android variants? 
> 
> ```
> 
>  buildTypes {
> 
>         debug {
> 
>             signingConfig signingConfigs.debug
> 
>             applicationIdSuffix ".dev"
> 
>         }
> 
>         release {
> 
>             // Caution! In production, you need to generate your own keystore file.
> 
>             // see https://reactnative.dev/docs/signed-apk-android.
> 
>             signingConfig signingConfigs.release
> 
>             applicationIdSuffix ".lava"
> 
>             minifyEnabled enableProguardInReleaseBuilds
> 
>             proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
> 
>         }
> 
>         releasestaging {
> 
>             initWith release
> 
>             applicationIdSuffix ".dev"
> 
>             matchingFallbacks = ['release']
> 
>         }
> 
>     }
> 
> ```

I use expo config to inject in app build.gradle base on ENV

**Comment by numandev1** [comment]
@barzin144 I was writing an expo plugin, but I am afraid that some package also had been making Android build variants and my package also has been making build variants then we can get conflict. what do you suggest?

![Screenshot 2023-09-07 at 3 24 47 PM](https://github.com/numandev1/react-native-keys/assets/36044436/5690f94e-cf43-4684-bebe-4197c90ec53e)

**Comment by chanphiromsok** [comment]
> @chanphiromsok I was writing an expo plugin, but I am afraid that some packages also had been making Android build variants and my package also has been making build variants then we can get into conflict. what do you suggest?
> 
> 
> 
> ![Screenshot 2023-09-07 at 3 24 47 PM](https://github.com/numandev1/react-native-keys/assets/36044436/5690f94e-cf43-4684-bebe-4197c90ec53e)
> 
> 

I have an idea but I can't write Regex 
-first read file app/build.gradle
- if other packages if modified this you need to use regex to check if it exist and don't override other plugins just append your content to variant
