### ISSUE TITLE
Expo Support should add

### ISSUE THREAD

**Issue by numandev1** [numandev1/react-native-keys#47]

**Comment by chanphiromsok** [comment]
Hello could you share me what to want to do ? may I can help you write expo plugins with expo prebuild

**Comment by numandev1** [comment]
@chanphiromsok I just wanna know about the expo user point of view into `app.config.json` + some edge cases, it would be good to have a little call on it, after that i will make it soon

**Comment by chanphiromsok** [comment]
> @chanphiromsok I just wanna know about the expo user point of view into `app.config.json` + some edge cases, it would be good to have a little call on it, after that i will make it soon

in `app.config.{js,ts,json}` it can use build base on `ENV (dev or prod)`  but the different is expo not encrypt when using in NativeModule like `google maps key`.

**Comment by numandev1** [comment]
@chanphiromsok should the user declare android product flavors with mapping of key files and ios scheme with mapping of key files like this?
```
{
  "name": "my app",
  "plugins": [
    [
      "react-native-keys",
      {
        "android": {
          "keyFiles": {
            "development": "keys.development.json",
            "production": "keys.development.json",
            "staging": "keys.development.json"
          },
          "productFlavors": {
            "development": {
              "applicationIdSuffix": ".dev1"
            },
            "staging": {
              "applicationIdSuffix": ".staging"
            },
            "production": {
              "applicationIdSuffix": ""
            }
          }
        },
        "ios": {
          "keyFiles": {
            "development": "keys.development.json",
            "production": "keys.development.json",
            "staging": "keys.development.json"
          },
          "schemes":{
            "dev": "development", //value is the keyFile name
            "staging": "staging",
            "prod": "production"
          }
        }
      }
    ]
  ]
}
```

**Comment by chanphiromsok** [comment]
I like to use one for one rather than map key/value 
- why one for one `keyFiles : process.env.NODE_ENV==="prod" ? keys.prod.json : keys.dev.json ` I think it clean and no need to put unnecessary json file if user running release but you put 3 json (dev,stag,prod) file to their build

**Comment by numandev1** [comment]
@chanphiromsok What if users have multiple environments, I also wanna use a clean solution from `app.config.json`, we should allow user to allow user to have multiple environments if he wants, can you suggest me any clean solution from `app.config.json`

**Comment by chanphiromsok** [comment]
> @chanphiromsok What if users have multiple environments, I also wanna use a clean solution from `app.config.json`, we should allow user to allow user to have multiple environments if he wants, can you suggest me any clean solution from `app.config.json`

if user want multiple environments  your https://github.com/numandev1/react-native-keys/issues/47#issuecomment-1719201015 solution is good to go and I can't say my ideas is right  I want you to know more about expo users perspective on your library

**Comment by numandev1** [comment]
@chanphiromsok thanks for helping me out❤
did you ever manage `ios scheme` or `productFlavors` into the expo?
how do you manage two environments in the expo?

I wanna make the simpler solution above mine solution is also looking complex to me

**Comment by chanphiromsok** [comment]
> @chanphiromsok thanks for helping me out❤ did you ever manage `ios scheme` or `productFlavors` into the expo? how do you manage two environments in the expo?
> 
> I wanna make the simpler solution above mine solution is also looking complex to me

I edit in the Xcode but it not better approach 😅

**Comment by numandev1** [comment]
@chanphiromsok hahaha if you edit into Xcode then build on the expo server using eas will not work, i don't know how expo user manage multiple environments into expo

**Comment by chanphiromsok** [comment]
> @chanphiromsok hahaha if you edit into Xcode then build on the expo server using eas will not work, i don't know how expo user manage multiple environments into expo

I use prebuilt our team is experiment expo now it use on prod 😅

**Comment by numandev1** [comment]
https://docs.expo.dev/build-reference/variables/
https://docs.expo.dev/guides/environment-variables/
they are managing different build environment like this, i have to make a solution where expo user can easily migrate to this pacage

**Comment by chanphiromsok** [comment]
this is I my plugins I write inject for code push for expo prebuild 
- in terminal I run `export env = prod` for production otherwise run `export env =dev` this is just example in my project using bash script for export env
- so that `const codepushIos =  env=== "prod" ? "keypord" : "keydev"` this my current code 
-  I follow the expo config I see a lot of expo plugin using one one key and did not ship  multiples keys to app `(dev & prod)`
```javascript
['./plugins/react-native-codepush',
  {
     iosDeploymentKey: codepushIos,
     androidDeploymentKey: codepushAndroid,
   },
 ]
```

**Comment by chanphiromsok** [comment]
Error expo plugin when installation
<img width="1091" alt="image" src="https://github.com/numandev1/react-native-keys/assets/65760336/72747ef7-5516-455f-a4e1-e64cbb8ea1e2">

**Comment by numandev1** [comment]
@chanphiromsok can you check `0.7.1`, sorry 🙏 i forget files line into package.json

**Comment by numandev1** [comment]
@chanphiromsok did you check?

**Comment by chanphiromsok** [comment]
> @chanphiromsok did you check?

Hi sorry for late response ,new fixed still error CommandError: Cannot find module 'walk-sync'

**Comment by numandev1** [comment]
@chanphiromsok sorry, I added `walk-sync` into `devDependencies` which was wrong, it should add `dependencies`. can you check `0.7.3` now? 🙏 🙏

**Comment by chanphiromsok** [comment]
> @chanphiromsok sorry, I added `walk-sync` into `devDependencies` which was wrong, it should add `dependencies`. can you check `0.7.3` now? 🙏 🙏

It work now but I wish you using plain node instead of external lib 😅
