### ISSUE TITLE
Xcode 15 Exited with status code 127

### ISSUE THREAD

**Issue by efstathiosntonas** [numandev1/react-native-keys#53]
### Current behavior
Hi, when I try to build on Xcode 15 it throws `Exited with status code 127`.  I've tried it on my project and the example project, both throw the same error.

See atached .txt for the logs, it seems that it exits on `/bin/sh -c /var/folders/tc/sj1dwpmd3wx006fkwntygshh0000gn/T/SchemeScriptAction-fuoWNX.sh`, I've tried to run the script on my terminal and it throws `No such file or directory` 

[Build KeysExample-Dev_2023-09-27T10-42-05.txt](https://github.com/numandev1/react-native-keys/files/12736059/Build.KeysExample-Dev_2023-09-27T10-42-05.txt)

### Platform

- [] Android
- [X] iOS

**Comment by numandev1** [comment]
@efstathiosntonas can you send the screenshot of your preaction script?

**Comment by numandev1** [comment]
@efstathiosntonas i tested, it is working on my side

![simulator_screenshot_67386EE3-6366-4EC1-87D8-F94238BA35BC](https://github.com/numandev1/react-native-keys/assets/36044436/7482fa34-005e-4708-b1d9-fca474c8c0fd)

**Comment by efstathiosntonas** [comment]
@numandev1 thanks for the fast reply. I'm running the example from this repo.

steps:
0. Sonoma 14
1. yarn install
2. cd example
3. yarn install
4. cd ios
5. pod install
6. open on Xcode
7. build on simulator iOS 17

I'm not doing anything else, I didn't touched the schemas. Really weird.

**Comment by efstathiosntonas** [comment]
I've runned it again, now it throws some more info at the ending lines of the log: 

```
    /bin/sh -c /var/folders/tc/sj1dwpmd3wx006fkwntygshh0000gn/T/SchemeScriptAction-sh6CQB.sh

env: node: No such file or directory
```

**Comment by numandev1** [comment]
if you are using nvm then please follow this guide https://github.com/numandev1/react-native-keys#using-node-with-nvm-fnm-or-notion

**Comment by efstathiosntonas** [comment]
Yeah, I suspected nvm is the issue this after the error above, looking into it now

**Comment by efstathiosntonas** [comment]
@numandev1 it's fine now, thank you for your help, keep it up!

**Comment by ustuncem** [comment]
In case this helps anyone, I wasn't using any of the version managers and just installed node directly using homebrew but I still got this error. Solved it by adding a control to the provided script in the link that if all fails, just use the value that is printed by `which node`. Here is my pre actions script:

```
export DEBUG_KEYSFILE=keys.debug.json
export RELEASE_KEYSFILE=keys.release.json

# Setup nvm if available
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
  . "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
  . "$(brew --prefix nvm)/nvm.sh"
fi

# Set up the nodenv node version manager if present
if [[ -x "$HOME/.nodenv/bin/nodenv" ]]; then
  eval "$("$HOME/.nodenv/bin/nodenv" init -)"
fi

# Set up the fnm node version manager if present
if [[ -s "$HOME/.fnm/fnm" ]]; then
  eval "`$HOME/.fnm/fnm env --multi`"
fi

# Trying Notion
if [ -z "$NODE_BINARY" ]; then
  if [[ -s "$HOME/.notion/bin/node" ]]; then
    export NODE_BINARY="$HOME/.notion/bin/node"
  fi
fi

# If all else fails, use the Homebrew-installed Node
if [ -z "$NODE_BINARY" ]; then
  export NODE_BINARY="$(which node)"
fi

$NODE_BINARY "${SRCROOT}/../node_modules/react-native-keys/keysIOS.js"
```

**Comment by ckotkar** [comment]
am still facing same issue after following https://github.com/numandev1/react-native-keys#using-node-with-nvm-fnm-or-notion, Can someone elaborate the steps to resolve this issue
