### ISSUE TITLE
[fix] crash in release mode (Android, proguard off)

### ISSUE THREAD

**Issue by talaikis** [numandev1/react-native-keys#67]
### Current behavior

**Working fine in debug mode**, On release crashes the app upon opening without errors.

### Expected behavior

Working release build.

### Platform

- [X] Android
- [] iOS

### React Native Version

0.72.6

### React Native Compressor Version

-

### Reproducible Steps And Demo

1. import 'react-native-keys'
2. Builld budnle or apk
3. Install on physical device or emulator
4. Open app

**Comment by numandev1** [comment]
which version, you are using for keys package, can you attach apk which is crashing?

**Comment by talaikis** [comment]
0.7.7-0.7.9, I'll try to make separate repro in a week, because this one is private and pretty huge. If that's conflict with some dependency, then it will take longer.

**Comment by numandev1** [comment]
@talaikis can you try to remove this file and test 

https://github.com/numandev1/react-native-keys/pull/66/files#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR159

**Comment by talaikis** [comment]
> @talaikis can you try to remove this line and test

That patch works.

**Comment by numandev1** [comment]
@talaikis released in `0.7.10`
