### ISSUE TITLE
IOS Xcode 15 archive failed

### ISSUE THREAD

**Issue by ngocle2497** [numandev1/react-native-keys#69]
### Current behavior
Archive failed when use xcode 15
### Platform

- [X] iOS

### React Native Version
0.72.2
Undefined symbols for architecture arm64:
  "_BIO_f_base64", referenced from:
      decryptor::base64_decode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libreact-native-keys.a(decryptor.o)
  "_BIO_free_all", referenced from:
      decryptor::base64_decode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libreact-native-keys.a(decryptor.o)
  "_BIO_new", referenced from:
      decryptor::base64_decode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libreact-native-keys.a(decryptor.o)
  "_BIO_new_mem_buf", referenced from:
      decryptor::base64_decode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libreact-native-keys.a(decryptor.o)
  "_BIO_push", referenced from:
      decryptor::base64_decode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libreact-native-keys.a(decryptor.o)
  "_BIO_read", referenced from:
      decryptor::base64_decode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libreact-native-keys.a(decryptor.o)
  "_BIO_set_flags", referenced from:
      decryptor::base64_decode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_BytesToKey", referenced from:
      decryptor::openSSLKey(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_CIPHER_CTX_free", referenced from:
      decryptor::rawDecrypt(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_CIPHER_CTX_new", referenced from:
      decryptor::rawDecrypt(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_CIPHER_iv_length", referenced from:
      decryptor::openSSLKey(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_CIPHER_key_length", referenced from:
      decryptor::openSSLKey(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_DecryptFinal_ex", referenced from:
      decryptor::rawDecrypt(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_DecryptInit_ex", referenced from:
      decryptor::rawDecrypt(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_DecryptUpdate", referenced from:
      decryptor::rawDecrypt(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_aes_256_cbc", referenced from:
      decryptor::rawDecrypt(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_get_cipherbyname", referenced from:
      decryptor::openSSLKey(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
  "_EVP_md5", referenced from:
      decryptor::openSSLKey(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) in libreact-native-keys.a(decryptor.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by numandev1** [comment]
@masonle2x2 can you try this solution 

https://stackoverflow.com/questions/29082174/ios-xcode-build-failing-due-to-openssl/76455587#76455587

**Comment by masonle2x2** [comment]
Thanks, i just add Open-SSL to pod file with modular-heasder. It work, please add this to trouble docs

**Comment by numandev1** [comment]
@masonle2x2 on some RN versions I get this issue but on some versions, I am not getting any issue, I think, Flipper is also using open SSL therefore we are getting issues like this, can you add trouble docs?
I added docs for this, you can improve it if you want


![Screenshot 2023-11-22 at 12 32 35 PM](https://github.com/numandev1/react-native-keys/assets/36044436/ac7c9ff7-edff-4d71-b60c-2d4240c6f493)

**Comment by masonle2x2** [comment]
> @masonle2x2 on some RN versions I get this issue but on some versions, I am not getting any issue, I think, Flipper is also using open SSL therefore we are getting issues like this, can you add trouble docs?
> I added docs for this, you can improve it if you want
> 
> 
> ![Screenshot 2023-11-22 at 12 32 35 PM](https://github.com/numandev1/react-native-keys/assets/36044436/ac7c9ff7-edff-4d71-b60c-2d4240c6f493)
> 

Thanks, but i hate Flipper .....
