### ISSUE TITLE
Use keys.dev.json instead?

### ISSUE THREAD

**Issue by dayaki** [numandev1/react-native-keys#78]
Thanks for this awesome package, I am just curious if it is possible to use my own naming convention for the json files? like `keys.dev.json`, `keys.prod.json`?

**Comment by ngocle2497** [comment]
> Thanks for this awesome package, I am just curious if it is possible to use my own naming convention for the json files? like `keys.dev.json`, `keys.prod.json`?

For android, u can use flavor. Or use
```
project.ext.keyFiles = [
debug: 'path to env',
release: 'path to env'
]
```
For ios, u can create new scheme to switch env file. Or use configuration to switch env:
```
if ["${CONFIGURATION}" = "Release"]; then
# load env for release
else
# load env for debug
fi
```

**Comment by dayaki** [comment]
awesome, got it to work.
